apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/galarconm/crud-devops-pipeline-v4
    targetRevision: feature/enterprise-networking
    path: k8s/pruebas-cni
  destination:
    server: https://kubernetes.default.svc
    namespace: pruebas-cni
  syncPolicy:
    automated:
      prune: true # Si eliminas un archivo de Git, ArgoCD elimina el recurso
      selfHeal: true # Si alguien hace kubectl apply manual, ArgoCD lo revierte
    syncOptions:
      - CreateNamespace=true # Crea el namespace si no existe
      - ServerSideApply=true
