apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/galarconm/crud-devops-pipeline-v4
    targetRevision: main
    path: k8s/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true  # Si eliminas un archivo de Git, ArgoCD elimina el recurso
      selfHeal: true # Si alguien hace kubectl apply manual, ArgoCD lo revierte
  syncOptions:
    - CreateNamespace=true # Crea el namespace si no existe
    - ServerSideApply=true # Es para que ArgoCD use Server-Side Apply,