apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    project: crud-devops-pipeline
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "20" # maximo numero de pods que pueden existir en el namespace
    requests.cpu: "2" # total cpu que todos los pods en el namespace pueden solicitar
    requests.memory: 2Gi # total memoria que todos los pods en el namespace pueden solicitar
    limits.cpu: "4" # maximo cpu que todos los pods en el namespace pueden usar
    limits.memory: 4Gi # maximo memoria que todos los pods en el namespace pueden usar
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev
spec:
  limits:
  - type: Container
    default:  # si el pod no especifica limits, se aplican estos valores por defecto
      cpu: "200m"
      memory: "256Mi"
    defaultRequest: # si el pod no especifica requests, se aplican estos valores por defecto
      cpu: "100m"
      memory: "128Mi"
