apiVersion: v1
kind: ServiceAccount
metadata:
  name: crud-backend-service-account #nombre del empleado
  namespace: dev #departamento
  annotations:
    #esta anotacion es lo que activa IRSA
    #eks.amazonaws.com/role-arn: arn:aws:eks:us-east-1:654654193269:cluster/crud-devops-pipeline-dev 
    eks.amazonaws.com/role-arn: arn:aws:iam::654654193269:role/crud-devops-pipeline-dev-backend-irsa-role
    eks.amazonaws.com/token-expiration: "86400"
